#include <stdio.h>
#include <conio.h>
#include <iostream.h>
main()
{
struct bulat
{
float jari;
float keliling;
float luas;
};
bulat lingkaran;
cout<<"Masukkan Jari-Jari Lingkaran :";
cin>>lingkara.jari;
lingkaran.keliling=2*3.14259*lingkaran.jari;
lingkaran.luas=3.14259*lingkaran.jari*lingkaran.jari;
cout<<"Keliling Lingkaran = "<<lingkaran.keliling;
cout<<"luas Lingkaran = "<<lingkaran.luas;
getch();
}